### ISSUE TITLE
create github action

### ISSUE THREAD

**Issue by nlf** [threatdown/threatdown-graph#10]
this action should be able to find a threatdown block, comment it out and replace it with either an embedded svg file or the mermaid code (behind an option)

we have a few possibilities for implementation here. one option is looking at [remark](https://github.com/remarkjs/remark) to see how difficult it might be to implement as a plugin. this would give us the greatest flexibility and i think is the direction we should ultimately head.

given our short timeline my backup plan, which is much less graceful, is to hack it directly into threatdown with some one-off functions to just regex the heck out of it.

whatever route we take, we want the ability to: 

1. accept a path to a markdown file (a glob probably would be best)
2. read all found markdown files
3. search for code blocks tagged threatdown (triple backtick start and end, with the word `threatdown` being present immediately after the start triple backtick)
4. generate an svg from the contents of each code block
5. comment out the code blocks in the original markdown file
6. insert an image reference to the relevant svg where the code block was

**Comment by Simon-Busch** [comment]
Info:

Linking this [PR](https://github.com/threatdown/threatdown-graph/pull/12) as the md converting functionality will be developed here

**Comment by Simon-Busch** [comment]
Once the mentionned PR will land, I will create the action here: https://github.com/threatdown/threatdown-converter-action and then make the repo public

**Comment by Simon-Busch** [comment]
I re-open the issue as this is only partly done, I need to create the action here now: https://github.com/threatdown/threatdown-converter-action

**Comment by Simon-Busch** [comment]
Done here: https://github.com/threatdown/threatdown-converter-action
